$M_k + M_l = M_1$ where $M_k$ and $M_l$ are matrices of size $h \times p$

$h$ is the height (rows) of the lock/key schematic, and $p$ are the number of pins in the lock/key.

$M_{k} \in KM$, the key matrix set

$M_{l} \in LM$, the lock matrix set

In [32]:
import numpy as np



def read_file(filename):
    km = []
    lm = []
    with open(filename) as f:
        lines = f.readlines()

        li = 0
        while li < len(lines):
            l_set = lines[li:li+7]
            li += 8
            if l_set[0] == '#####\n':
                lm.append([[(1 if k == '#' else 0) for k in r.strip()] for r in l_set])
            else:
                km.append([[(1 if k == '#' else 0) for k in r.strip()] for r in l_set])

    return np.array(km), np.array(lm)

km, lm = read_file('example.txt')

In [33]:
assert km.shape == (3, 7, 5), km.shape
assert lm.shape == (2, 7, 5), lm.shape

print(lm[0])
print(km[2])

def can_fit(key, lock):
    overlap = key + lock
    # any value > 1 means there is a conflict
    return np.all(overlap <= 1)

assert can_fit(lm[0], km[2]) == True
assert can_fit(lm[0], km[1]) == False

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 1 0 0]
 [1 0 1 0 1]
 [1 1 1 1 1]]


In [34]:
count = 0
for lmi in lm:
    for kmi in km:
        if can_fit(lmi, kmi):
            count += 1

assert count == 3

In [36]:
km, lm = read_file('input.txt')

count = 0
for lmi in lm:
    for kmi in km:
        if can_fit(lmi, kmi):
            count += 1

print(count)

3287
